# set reload keybindgs
unbind r
bind r source-file ~/.tmux.conf \; display-message "#[fg=yellow]✨ Config reloaded!"

set -g mouse on
set -g mode-keys vi
set -g history-limit 20000

# Index windows from 1
set -g base-index 1

# Auto Renumber windows after updating.
set -g renumber-windows on


# Enable mouse
set -g mouse on

set -g status on
set -g status-bg "default"
set -g status-fg "default"

set -g status-right ""

# set -g status-position top

# Auto-Rename Windows to CWD
set -g automatic-rename on
set -g automatic-rename-format "#{b:pane_current_path}"

# Status bar: no background, inherit terminal
set -g status-style bg=default,fg=default

# Clear left/right sections
set -g status-left-style bg=default,fg=default
set -g status-right-style bg=default,fg=default

# Window tabs
set -g window-status-style bg=default,fg=default
set -g window-status-current-style bg=default,fg=default

# Command prompt (:) — remove background
set -g message-style bg=default,fg=default

# Command mode input (the text you type)
set -g message-command-style bg=default,fg=default

# TMUX QUICK SWITCH SESSION

bind s display-popup -E -w 40% -h 40% -S "fg=#282828" -b rounded \
          "tmux list-sessions -F '#S' | fzf --reverse --border=none \
          --prompt='  ' --pointer='▌' --no-scrollbar \
          | xargs -I{} tmux switch-client -t {}"
